name: Deploy Cellcart to EC2

on:
  push:
    branches:
      - main  # Make sure this matches your default branch

jobs:
  deploy:
    runs-on: self-hosted  # 👈 IMPORTANT: Use self-hosted runner

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 50.17.7.158 >> ~/.ssh/known_hosts

      - name: Deploy to EC2 and Restart Docker
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@50.17.7.158 << 'EOF'
            cd /home/ec2-user/cellcart
            git pull origin main
            docker compose --env-file .env pull || true
            docker compose --env-file .env up --build -d
          EOF
