name: Deploy Cellcart to EC2

on:
  push:
    branches:
      - main  # Make sure you're pushing to this branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.196.184.196cd >> ~/.ssh/known_hosts

      - name: Deploy to EC2 and Restart Docker
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@54.196.184.19 << 'EOF'
            cd /home/ec2-user/cellcart
            git pull origin main
            docker compose --env-file .env pull || true
            docker compose --env-file .env up --build -d
          EOF
